site_name: HeartBioPortal DataHub
nav:
  - Overview: index.md
  - Submitting Data: submitting.md
  - Validation Guide: validation.md
  - Schema Reference: schema_reference.md
  - Processing Very Large Datasets: big_data_processing.md
  - FAQ: faq.md
